use axum::http::{StatusCode, header};
use axum::response::{IntoResponse, Response};
use rust_embed::Embed;

/// Embedded frontend assets compiled from `frontend/dist/`.
#[derive(Embed)]
#[folder = "frontend/dist/"]
pub struct Assets;

/// Serve a static file from embedded assets, with SPA fallback to `index.html`.
pub async fn static_handler(uri: axum::http::Uri) -> Response {
    let path = uri.path().trim_start_matches('/');

    // Try the exact path first, then fall back to index.html for SPA routing.
    match serve_asset(path) {
        Some(response) => response,
        None => match serve_asset("index.html") {
            Some(response) => response,
            None => StatusCode::NOT_FOUND.into_response(),
        },
    }
}

/// Look up an embedded asset by path and return it with appropriate headers.
fn serve_asset(path: &str) -> Option<Response> {
    let asset = Assets::get(path)?;
    let mime = mime_guess::from_path(path).first_or_octet_stream();

    let cache_control = if path == "index.html" {
        "no-cache"
    } else if path.contains('.') && (path.contains("-") || path.contains("_")) {
        // Hashed filenames generated by Vite get immutable caching.
        "public, immutable, max-age=31536000"
    } else {
        "public, max-age=3600"
    };

    Response::builder()
        .header(header::CONTENT_TYPE, mime.as_ref())
        .header(header::CACHE_CONTROL, cache_control)
        .body(axum::body::Body::from(asset.data.to_vec()))
        .ok()
}
